apiVersion: 1

datasources:
  - name: Auralake
    uid: auralake_pg
    type: postgres
    access: proxy
    url: db:5432
    user: $AURALAKE_DB_USER
    jsonData:
      database: $AURALAKE_DB_NAME
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $AURALAKE_DB_PASSWORD
    isDefault: true
    editable: false
