"""Diff rendering for pull request descriptions."""

from __future__ import annotations

import difflib

from auralake_shared.models.dab import DABDiff


def render_diff(dab_diff: DABDiff) -> str:
    """Render a DABDiff as a markdown code block with unified diff."""
    diff_lines = difflib.unified_diff(
        dab_diff.original_content.splitlines(keepends=True),
        dab_diff.modified_content.splitlines(keepends=True),
        fromfile=f"a/{dab_diff.file_path}",
        tofile=f"b/{dab_diff.file_path}",
    )
    diff_text = "".join(diff_lines)
    if not diff_text:
        return f"No changes in `{dab_diff.file_path}`"
    return f"```diff\n{diff_text}\n```"


def render_pr_body(
    summary: str,
    diffs: list[DABDiff],
    estimated_savings: float,
    evidence: dict | None = None,
) -> str:
    """Build a full PR body with summary, diffs, and savings estimate."""
    sections = [
        "## Summary",
        summary,
        "",
        f"**Estimated monthly savings:** ${estimated_savings:,.2f}",
        "",
    ]

    if diffs:
        sections.append("## Changes")
        for diff in diffs:
            sections.append(f"### {diff.description}")
            sections.append(render_diff(diff))
            sections.append("")

    if evidence:
        sections.append("## Evidence")
        for key, value in evidence.items():
            sections.append(f"- **{key}:** {value}")
        sections.append("")

    sections.append("---")
    sections.append("*Generated by [Aura Lake](https://github.com/auralake/auralake)*")

    return "\n".join(sections)
